name: taxi2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.3+3
  firebase_database: ^3.1.1
  http: ^0.12.0+2
  nima: ^1.0.5
  background_location:
  flutter_secure_storage:
  permission_handler:
  geo:

  provider: ^4.0.2
  connectivity: ^0.4.3+7
  shared_preferences: ^0.5.3+4


  #cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:
  assets:
      - assets/icon.png
      - assets/anims/nimaTest.nima
      - assets/anims/nimaTest.png

  uses-material-design: true

