name: taxi2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.4.0
  background_location:
  flutter_secure_storage:
  http: ^0.12.0+2
  permission_handler:
  geo:

  provider: ^4.0.2
  get_it: ^2.0.1
  equatable: ^0.4.0
  dartz: ^0.8.6
  connectivity: ^0.4.3+7
  shared_preferences: ^0.5.3+4


  #cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:

  uses-material-design: true

